version: '3'
services:
  client:
    build: ./client
    ports:
      - '3000:80'
  server:
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
volumes:
  mongo-data:
